 devices: 
    cat8k-rt1: 
        1: 
          config: /path/to/my/configuration 
          sleep: 3 
          invalid: ['overlaps', '(.*inval.*)'] 
        2: 
          jinja2_config: config_templates/routing.j2 
          jinja2_arguments: 
            lstrip_blocks: true 
            trim_blocks: true 
            bgp_data: 
                bgp_as: 100 
                neighbor_ips: [ 
                    '1.1.1.1', '2.2.2.2' 
                ] 
          configure_arguments: 
            bulk: True 
            timeout: 180
# Skip checking interface descriptions when comparing config snapshots
exclude_config_check: ['(.*description.*)'] 